### ISSUE TITLE
error: unexpected close delimiter: `]` 

### ISSUE THREAD

**Issue by devurandom** [rust-onig/rust-onig#120] opened 2019-09-29 08:36 UTC
When trying to build bat v0.12.0, onig_sys v69.2.0 fails to build:
```
   Compiling onig_sys v69.2.0                                                
error: unexpected close delimiter: `]` 
    --> /tmp/portage/sys-apps/bat-0.12.0/work/bat-0.12.0/target/release/build/onig_sys-37cac6ba10c63575/out/bindings.rs:1389:32
     |                              
1389 | #[derive(Copy, Clone)]; 2usize ] , }#[repr(C)]
     |                                ^ unexpected close delimiter
                                                                                           
error: aborting due to previous error
                                                                                           
error: Could not compile `onig_sys`.     
```

Oniguruma is at v6.9.3, Rust at v1.38.0.

* [build.log](https://github.com/rust-onig/rust-onig/files/3666531/build.log)
* [emerge --info bat oniguruma](https://github.com/rust-onig/rust-onig/files/3666532/emerge.info.txt)

See-Also: https://bugs.gentoo.org/695844

**Comment by iwillspeak** [comment] 2019-10-01 06:29
This looks like it might be a bug in the `bindgen` crate. I'm going to be doing some work soon around how we use bindgen. Hopefully updating to the latest `bindgen` will fix this. In the mean time it might be worth opening a bug with [`bindgen`](https://github.com/rust-lang/rust-bindgen) too.

**Comment by devurandom** [comment] 2019-10-01 20:49
I am looking at the bug reporting template for bindgen and do not feel that I can easily fill it, lacking an MWE and time to dive into rust-onig's invocation of bindgen. I will instead also hope that updating bindgen will fix this. ;)

**Comment by devurandom** [comment] 2019-10-04 12:19
I think this might be a parallel build issue. I put my machine under a lot of load (which reduces the number of concurrent compiler invocations, as a side effect) and now bat-0.12.0 compiles fine.

**Comment by devurandom** [comment] 2019-10-04 15:22
I am now unable to reproduce this, after it was reproducible for weeks.

I rebuilt rust 1.38.0 to include clippy, rustfmt and wasm support. Then I tried building bat 0.12.0 with `RUSTONIG_SYSTEM_LIBONIG=1` set to compile against the system dev-libs/oniguruma-6.9.3-r1. This did not work initially (see #124 and #125), but after those issues were fixed, bat built and now it keeps building no matter what I do... (Even if I remove the patches and try to build against the bundled oniguruma, it still builds.)

Please feel free to close, unless you can reproduce or have an idea for why this happened.

**Comment by iwillspeak** [comment] 2019-10-04 16:25
Thanks for the update. I didn’t reproduce this. Closing

**Closed by iwillspeak** 2019-10-04 16:25 UTC
Labels: Crate-Onig_Sys, T-Bug
